#include <iostream>
#include <exception>
#include <stdexcept>
#include "Header.h"


using std::cout; using std::cin; using std::endl; using std::cout; using std::exception;


int main()
{
	/*
		std::vector<int> myvector(10);
		try {
			myvector.at(20) = 100;      // vector::at throws an out-of-range
		}
		catch (const std::out_of_range& oor) {
			cout << "Out of Range error: " << oor.what() << '\n';
		}
		try {



		}

		system("pause");
		return 0;
	
	*/
	heady ajo;
	ajo.laitaVektoriin();

	system("pause");
	return 0;

}